// <auto-generated />
using System;
using GeradorNotaFiscal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeradorNotaFiscal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121231722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GeradorNotaFiscal.models.Invoice", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("emissionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("invoiceNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("invoiceValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("paymentId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("paymentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("GeradorNotaFiscal.models.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("clientDocument")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("clientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<decimal>("totalValue")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GeradorNotaFiscal.models.Payment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("orderId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("paymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("paymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<decimal>("valuePaid")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.HasIndex("orderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GeradorNotaFiscal.models.Invoice", b =>
                {
                    b.HasOne("GeradorNotaFiscal.models.Payment", "payment")
                        .WithMany()
                        .HasForeignKey("paymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("payment");
                });

            modelBuilder.Entity("GeradorNotaFiscal.models.Payment", b =>
                {
                    b.HasOne("GeradorNotaFiscal.models.Order", "order")
                        .WithMany()
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");
                });
#pragma warning restore 612, 618
        }
    }
}
